insert into t_informativo_saude values ( 1 , '2017-08-02' , ' Lorem ipsum dolor sit amet, consectetur adipiscing elit. ' , 1 );
insert into t_informativo_saude values ( 2 , '2018-04-20' , ' Fusce ut tortor et lorem facilisis cursus sodales nec leo. ' , 2 );
insert into t_informativo_saude values ( 3 , '2017-09-06' , ' Vestibulum nec velit eget dolor aliquam auctor. ' , 3 );
insert into t_informativo_saude values ( 4 , '2017-10-19' , ' Curabitur eu nunc feugiat, efficitur ante et, rhoncus felis. ' , 4 );
insert into t_informativo_saude values ( 5 , '2017-12-16' , ' Fusce hendrerit sapien id risus aliquet, sit amet dapibus tortor lobortis. ' , 5 );
insert into t_informativo_saude values ( 6 , '2018-05-22' , ' Duis rhoncus felis eu dui elementum fringilla. ' , 6 );
insert into t_informativo_saude values ( 7 , '2015-02-09' , ' Praesent et ligula sit amet ipsum consequat congue. ' , 7 );
insert into t_informativo_saude values ( 8 , '2018-03-26' , ' Nam luctus massa vitae volutpat laoreet. ' , 8 );
insert into t_informativo_saude values ( 9 , '2015-06-24' , ' Suspendisse vel ante pulvinar, dapibus felis at, tristique lorem. ' , 9 );
insert into t_informativo_saude values ( 10 , '2018-06-09' , ' Sed vulputate justo ut iaculis volutpat. ' , 10 );
insert into t_informativo_saude values ( 11 , '2015-10-13' , ' Pellentesque egestas nisl quis lectus molestie auctor at at augue. ' , 11 );
insert into t_informativo_saude values ( 12 , '2017-06-17' , ' Nullam mattis libero in ex egestas, sed lacinia diam varius. ' , 12 );
insert into t_informativo_saude values ( 13 , '2017-08-14' , ' Integer feugiat velit sed massa ornare lobortis. ' , 13 );
insert into t_informativo_saude values ( 14 , '2017-08-07' , ' Fusce et est sed ante consequat malesuada. ' , 14 );
insert into t_informativo_saude values ( 15 , '2017-11-19' , ' Curabitur eu metus a nunc ultricies porta sed vitae lorem. ' , 15 );
insert into t_informativo_saude values ( 16 , '2017-08-07' , ' Integer ut felis ut felis accumsan sodales vel quis risus. ' , 16 );
insert into t_informativo_saude values ( 17 , '2015-11-21' , ' Nullam at odio sit amet nisi lacinia facilisis. ' , 17 );
insert into t_informativo_saude values ( 18 , '2017-09-05' , ' Morbi elementum tortor sed nulla ullamcorper, ut vulputate lectus porttitor. ' , 18 );
insert into t_informativo_saude values ( 19 , '2017-03-30' , ' Aenean vitae sem sed quam tempor euismod. ' , 19 );
insert into t_informativo_saude values ( 20 , '2017-09-22' , ' Proin et dui lobortis, scelerisque urna vitae, posuere urna. ' , 20 );
insert into t_informativo_saude values ( 21 , '2018-08-20' , ' Fusce suscipit erat at odio commodo mollis. ' , 21 );
insert into t_informativo_saude values ( 22 , '2015-08-15' , ' Suspendisse sagittis tortor ut lacinia tristique. ' , 22 );
insert into t_informativo_saude values ( 23 , '2018-08-28' , ' Quisque ornare libero ullamcorper quam tincidunt, vitae efficitur ipsum condimentum. ' , 23 );
insert into t_informativo_saude values ( 24 , '2017-01-29' , ' Cras vitae urna pharetra, ultricies nibh et, malesuada mauris. ' , 24 );
insert into t_informativo_saude values ( 25 , '2018-01-03' , ' Fusce vitae turpis id tortor euismod pretium maximus in urna. ' , 25 );
insert into t_informativo_saude values ( 26 , '2017-11-18' , ' Cras vitae metus ac dui facilisis aliquet. ' , 26 );
insert into t_informativo_saude values ( 27 , '2016-05-02' , ' Vivamus quis magna in massa laoreet luctus. ' , 27 );
insert into t_informativo_saude values ( 28 , '2016-01-27' , ' Fusce vulputate neque laoreet, venenatis velit nec, congue tellus. ' , 28 );
insert into t_informativo_saude values ( 29 , '2017-04-06' , ' Cras ut tortor non ipsum facilisis feugiat. ' , 29 );
insert into t_informativo_saude values ( 30 , '2015-12-25' , ' Pellentesque vitae leo sit amet erat pharetra molestie quis in libero. ' , 30 );
insert into t_informativo_saude values ( 31 , '2018-07-11' , ' Vivamus eu mi nec justo efficitur laoreet. ' , 31 );
insert into t_informativo_saude values ( 32 , '2015-09-09' , ' Aenean et ex et augue sodales aliquet vel vitae est. ' , 32 );
insert into t_informativo_saude values ( 33 , '2017-12-02' , ' Sed interdum ante vitae sem iaculis, quis commodo turpis blandit. ' , 33 );
insert into t_informativo_saude values ( 34 , '2015-06-05' , ' Praesent ac eros eget metus ornare tempus a vel quam. ' , 34 );
insert into t_informativo_saude values ( 35 , '2016-11-26' , ' Mauris at ligula ut orci tristique elementum et at est. ' , 35 );
insert into t_informativo_saude values ( 36 , '2018-08-15' , ' Vivamus in dui sed orci bibendum vestibulum. ' , 36 );
insert into t_informativo_saude values ( 37 , '2017-07-12' , ' Nulla at leo ut metus hendrerit rhoncus vel eu eros. ' , 37 );
insert into t_informativo_saude values ( 38 , '2015-10-02' , ' Sed vel magna dictum, ullamcorper enim in, rhoncus mi. ' , 38 );
insert into t_informativo_saude values ( 39 , '2018-07-02' , ' Ut quis justo iaculis, consequat erat et, laoreet justo. ' , 39 );
insert into t_informativo_saude values ( 40 , '2016-10-12' , ' Duis in mi ac mi laoreet consectetur. ' , 40 );
insert into t_informativo_saude values ( 41 , '2016-01-10' , ' Vivamus ac velit ultrices, imperdiet dui sed, venenatis mi. ' , 41 );
insert into t_informativo_saude values ( 42 , '2015-10-29' , ' Nullam vitae metus nec augue pretium convallis vitae sit amet mi. ' , 42 );
insert into t_informativo_saude values ( 43 , '2015-04-04' , ' Aliquam accumsan massa et massa dictum vehicula. ' , 43 );
insert into t_informativo_saude values ( 44 , '2015-03-28' , ' Vestibulum porta nibh ut eros dapibus, dictum semper augue pretium. ' , 44 );
insert into t_informativo_saude values ( 45 , '2017-02-20' , ' Proin sodales libero a ante consectetur condimentum. ' , 45 );
insert into t_informativo_saude values ( 46 , '2016-06-15' , ' Aliquam non eros non justo placerat venenatis. ' , 46 );
insert into t_informativo_saude values ( 47 , '2018-02-05' , ' Aliquam commodo purus id felis dignissim eleifend. ' , 47 );
insert into t_informativo_saude values ( 48 , '2015-11-04' , ' Mauris semper ante vitae leo mollis vehicula. ' , 48 );
insert into t_informativo_saude values ( 49 , '2015-11-15' , ' Donec bibendum dolor eu ex efficitur, feugiat tempus risus suscipit. ' , 49 );
insert into t_informativo_saude values ( 50 , '2018-08-29' , ' Donec tempor neque pharetra, feugiat nulla ac, pharetra quam. ' , 50 );


SELECT * FROM t_informativo_saude;