insert into T_NOTIFICACAO  values ( 1 , '2018-03-12' ,  ' Lorem ipsum dolor sit amet, consectetur adipiscing elit.  ' , 1 );
insert into T_NOTIFICACAO  values ( 2 , '2018-05-17' ,  ' Aliquam dictum arcu eget neque finibus, id consectetur lacus ullamcorper.  ' , 2 );
insert into T_NOTIFICACAO  values ( 3 , '2017-06-06' ,  ' Mauris sed felis sit amet velit vehicula rhoncus eu a felis.  ' , 3 );
insert into T_NOTIFICACAO  values ( 4 , '2016-02-08' ,  ' Maecenas mattis ligula ut ligula aliquet, ut lacinia odio commodo.  ' , 4 );
insert into T_NOTIFICACAO  values ( 5 , '2017-02-24' ,  ' Nam vitae felis malesuada, fermentum augue vitae, laoreet sem.  ' , 5 );
insert into T_NOTIFICACAO  values ( 6 , '2016-01-02' ,  ' Sed vitae leo molestie, tempor odio ut, dignissim felis.  ' , 6 );
insert into T_NOTIFICACAO  values ( 7 , '2017-06-08' ,  ' Aenean in sapien at mi tempus iaculis.  ' , 7 );
insert into T_NOTIFICACAO  values ( 8 , '2016-02-18' ,  ' Morbi efficitur mauris vitae orci suscipit, sed tincidunt dui viverra.  ' , 8 );
insert into T_NOTIFICACAO  values ( 9 , '2017-08-31' ,  ' Vivamus tristique orci ut eros feugiat mollis.  ' , 9 );
insert into T_NOTIFICACAO  values ( 10 , '2016-06-05' ,  ' Aenean congue orci at elit venenatis suscipit.  ' , 10 );
insert into T_NOTIFICACAO  values ( 11 , '2016-01-20' ,  ' Etiam iaculis magna ut libero malesuada elementum.  ' , 11 );
insert into T_NOTIFICACAO  values ( 12 , '2018-06-08' ,  ' Aenean lobortis mi eu sagittis eleifend.  ' , 12 );
insert into T_NOTIFICACAO  values ( 13 , '2015-03-15' ,  ' Nullam fermentum tortor sit amet porttitor tincidunt.  ' , 13 );
insert into T_NOTIFICACAO  values ( 14 , '2015-12-02' ,  ' Curabitur egestas sapien vitae metus porttitor, eu porta orci pretium.  ' , 14 );
insert into T_NOTIFICACAO  values ( 15 , '2016-10-07' ,  ' Ut in magna congue, vestibulum lacus semper, rutrum purus.  ' , 15 );
insert into T_NOTIFICACAO  values ( 16 , '2015-10-16' ,  ' Cras tempus libero ut nisl efficitur, ac euismod velit laoreet.  ' , 16 );
insert into T_NOTIFICACAO  values ( 17 , '2018-01-24' ,  ' Suspendisse eget nisl non neque facilisis efficitur.  ' , 17 );
insert into T_NOTIFICACAO  values ( 18 , '2016-08-16' ,  ' Aliquam pretium risus et semper vulputate.  ' , 18 );
insert into T_NOTIFICACAO  values ( 19 , '2017-04-19' ,  ' Ut maximus nulla a sodales sagittis.  ' , 19 );
insert into T_NOTIFICACAO  values ( 20 , '2018-06-29' ,  ' Vestibulum vel massa iaculis, mollis eros nec, volutpat augue.  ' , 20 );
insert into T_NOTIFICACAO  values ( 21 , '2016-12-06' ,  ' Suspendisse non nunc molestie velit dignissim fringilla nec facilisis lacus.  ' , 21 );
insert into T_NOTIFICACAO  values ( 22 , '2018-05-13' ,  ' Aenean pretium mi ac turpis cursus rhoncus.  ' , 22 );
insert into T_NOTIFICACAO  values ( 23 , '2017-01-28' ,  ' Nam rhoncus nulla et nisi scelerisque auctor.  ' , 23 );
insert into T_NOTIFICACAO  values ( 24 , '2017-03-20' ,  ' Nullam convallis justo id pharetra pulvinar.  ' , 24 );
insert into T_NOTIFICACAO  values ( 25 , '2018-04-22' ,  ' Sed fermentum lorem non risus tristique, sit amet efficitur enim facilisis.  ' , 25 );
insert into T_NOTIFICACAO  values ( 26 , '2018-10-03' ,  ' Cras condimentum lorem non pulvinar tempus.  ' , 26 );
insert into T_NOTIFICACAO  values ( 27 , '2018-05-11' ,  ' Etiam eget lectus et lectus ultricies egestas.  ' , 27 );
insert into T_NOTIFICACAO  values ( 28 , '2016-03-06' ,  ' Sed in quam ut eros ultricies commodo non in mauris.  ' , 28 );
insert into T_NOTIFICACAO  values ( 29 , '2016-08-28' ,  ' Proin dignissim erat interdum cursus lobortis.  ' , 29 );
insert into T_NOTIFICACAO  values ( 30 , '2016-01-11' ,  ' Fusce porta lectus sodales, vestibulum nibh fringilla, vestibulum eros.  ' , 30 );
insert into T_NOTIFICACAO  values ( 31 , '2018-08-21' ,  ' Ut id dolor sagittis, dictum leo id, feugiat tellus.  ' , 31 );
insert into T_NOTIFICACAO  values ( 32 , '2018-09-07' ,  ' Ut pretium neque eu sem suscipit, at blandit ipsum fringilla.  ' , 32 );
insert into T_NOTIFICACAO  values ( 33 , '2015-12-15' ,  ' Pellentesque aliquam magna non ullamcorper auctor.  ' , 33 );
insert into T_NOTIFICACAO  values ( 34 , '2018-07-07' ,  ' Donec faucibus est ac vulputate placerat.  ' , 34 );
insert into T_NOTIFICACAO  values ( 35 , '2018-01-02' ,  ' Aenean auctor lectus vitae neque consectetur, vitae auctor lacus dapibus.  ' , 35 );
insert into T_NOTIFICACAO  values ( 36 , '2015-08-17' ,  ' Praesent nec quam et mi dictum dapibus.  ' , 36 );
insert into T_NOTIFICACAO  values ( 37 , '2016-03-26' ,  ' Vestibulum sed tellus commodo nibh tempus finibus.  ' , 37 );
insert into T_NOTIFICACAO  values ( 38 , '2016-09-09' ,  ' Nam imperdiet mauris quis metus viverra suscipit.  ' , 38 );
insert into T_NOTIFICACAO  values ( 39 , '2015-04-07' ,  ' Nam scelerisque mi a nisi accumsan, id eleifend lacus commodo.  ' , 39 );
insert into T_NOTIFICACAO  values ( 40 , '2015-03-04' ,  ' Sed faucibus lacus sit amet pharetra rutrum.  ' , 40 );
insert into T_NOTIFICACAO  values ( 41 , '2016-12-21' ,  ' Nunc tristique ex tempor odio dapibus vehicula et id lacus.  ' , 41 );
insert into T_NOTIFICACAO  values ( 42 , '2016-10-26' ,  ' Suspendisse pretium lectus quis orci tristique bibendum.  ' , 42 );
insert into T_NOTIFICACAO  values ( 43 , '2016-08-06' ,  ' Morbi sed odio nec magna malesuada malesuada.  ' , 43 );
insert into T_NOTIFICACAO  values ( 44 , '2015-10-13' ,  ' Donec vitae mauris sollicitudin, porttitor mi quis, porttitor urna.  ' , 44 );
insert into T_NOTIFICACAO  values ( 45 , '2015-07-13' ,  ' Nulla interdum felis vel nulla vestibulum, vitae maximus neque scelerisque.  ' , 45 );
insert into T_NOTIFICACAO  values ( 46 , '2018-05-24' ,  ' Suspendisse congue nibh in enim tincidunt, non tempor orci faucibus.  ' , 46 );
insert into T_NOTIFICACAO  values ( 47 , '2016-12-12' ,  ' Maecenas interdum massa vitae nisl mattis auctor.  ' , 47 );
insert into T_NOTIFICACAO  values ( 48 , '2016-11-22' ,  ' Praesent nec enim et massa rhoncus aliquet.  ' , 48 );
insert into T_NOTIFICACAO  values ( 49 , '2015-11-23' ,  ' Integer id sapien viverra, imperdiet nibh sed, finibus risus.  ' , 49 );
insert into T_NOTIFICACAO  values ( 50 , '2017-01-04' ,  ' Cras porttitor lorem at ex dapibus varius.  ' , 50 );


/* select * from t_notificacao; */