-- Generated by Oracle SQL Developer Data Modeler 18.2.0.179.0756
--   at:        2018-09-24 20:42:14 BRT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g

CREATE TABLE dim_faixa_etaria (
    sk_faixa_etaria    NUMBER(8) NOT NULL,
    nr_idade_inicial   NUMBER(3) NOT NULL,
    nr_idade_final     NUMBER(3) NOT NULL,
    nm_faixa_etaria    VARCHAR2(30) NOT NULL
);

ALTER TABLE dim_faixa_etaria ADD CONSTRAINT dim_faixa_etaria_pk PRIMARY KEY ( sk_faixa_etaria );

CREATE TABLE dim_imc (
    sk_imc   NUMBER(8) NOT NULL,
    tp_imc   VARCHAR2(30) NOT NULL
);

ALTER TABLE dim_imc ADD CONSTRAINT dim_imc_pk PRIMARY KEY ( sk_imc );

CREATE TABLE dim_pessoa (
    sk_pessoa         NUMBER(8) NOT NULL,
    id_pessoa         VARCHAR2(4) NOT NULL,
    nm_pessoa         VARCHAR2(60) NOT NULL,
    nr_dia_nasc       NUMBER(2) NOT NULL,
    nr_mes_nasc       NUMBER(2) NOT NULL,
    nr_ano_nasc       NUMBER(4) NOT NULL,
    nr_dia_cadastro   NUMBER(2) NOT NULL,
    nr_mes_cadastro   NUMBER(2) NOT NULL,
    nr_ano_cadastro   NUMBER(4) NOT NULL,
    nm_sexo           VARCHAR2(20) NOT NULL,
    nr_altura         NUMBER(3,2) NOT NULL,
    nr_peso           NUMBER(3,2) NOT NULL
);

ALTER TABLE dim_pessoa ADD CONSTRAINT dim_pessoa_pk PRIMARY KEY ( sk_pessoa );

CREATE TABLE dim_tempo (
    sk_tempo        NUMBER(8) NOT NULL,
    dt_data         DATE NOT NULL,
    nr_dia          NUMBER(2) NOT NULL,
    nr_mes          NUMBER(2) NOT NULL,
    nr_ano          NUMBER(4) NOT NULL,
    nm_mes          VARCHAR2(20) NOT NULL,
    nm_dia_semana   VARCHAR2(20) NOT NULL,
    nr_quinzena     NUMBER(2) NOT NULL,
    br_bimestre     NUMBER(2) NOT NULL,
    nr_trimestre    NUMBER(2) NOT NULL,
    nr_semestre     NUMBER(2) NOT NULL,
    dt_feriado      DATE NOT NULL
);

ALTER TABLE dim_tempo ADD CONSTRAINT dim_tempo_pk PRIMARY KEY ( sk_tempo );

CREATE TABLE fto_respostas_questionarios (
    sk_respostas      NUMBER(8) NOT NULL,
    qt_agua           NUMBER(4) NOT NULL,
    qt_estresse       NUMBER(4) NOT NULL,
    vl_med_estresse   NUMBER(5,2) NOT NULL,
    vl_imc            NUMBER(5,2) NOT NULL,
    sk_pessoa         NUMBER(8) NOT NULL,
    sk_tempo          NUMBER(8) NOT NULL,
    sk_imc            NUMBER(8) NOT NULL,
    sk_faiza_etaria   NUMBER(8) NOT NULL
);

ALTER TABLE fto_respostas_questionarios ADD CONSTRAINT fto_respostas_questionarios_pk PRIMARY KEY ( sk_respostas );

ALTER TABLE fto_respostas_questionarios
    ADD CONSTRAINT dim_faixa_etaria_fk FOREIGN KEY ( sk_faiza_etaria )
        REFERENCES dim_faixa_etaria ( sk_faixa_etaria );

ALTER TABLE fto_respostas_questionarios
    ADD CONSTRAINT dim_imc_fk FOREIGN KEY ( sk_imc )
        REFERENCES dim_imc ( sk_imc );

ALTER TABLE fto_respostas_questionarios
    ADD CONSTRAINT dim_pessoa_fk FOREIGN KEY ( sk_pessoa )
        REFERENCES dim_pessoa ( sk_pessoa );

ALTER TABLE fto_respostas_questionarios
    ADD CONSTRAINT dim_tempo_fk FOREIGN KEY ( sk_tempo )
        REFERENCES dim_tempo ( sk_tempo );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             5
-- CREATE INDEX                             0
-- ALTER TABLE                              9
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
